<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class Niveau8 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('Niveau')->insert([
            'id' => 8,
            'levelJson' => '{
                {
                    "id":8,
                    "nbCouleur":2,
                    "fonctions":[
                       {
                          "idFonction":1,
                          "nombreCase":3
                       },
                       {
                          "idFonction":2,
                          "nombreCase":4
                       }
                       ],
                      
                       "rotationStart": "fa-rotate-270",
                       "paint":true,
                    
                    "lignes":[
                       {
                          "idLigne":1,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":2,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":3,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":4,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":5,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":true,
                                "departBool":false,
                                "couleur":"bg-gray-800",
                                "visible":true
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"bg-gray-400",
                                "visible":true
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":9,
                                "etoileBool":true,
                                "departBool":false,
                                "couleur":"bg-gray-800",
                                "visible":true
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":6,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":7,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":8,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":true,
                                "couleur":"",
                                "visible":true
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":9,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       },
                       {
                          "idLigne":10,
                          "cases":[
                             {
                                "idCase":1,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":2,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":3,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":4,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":5,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":6,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":7,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":8,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":9,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             },
                             {
                                "idCase":10,
                                "etoileBool":false,
                                "departBool":false,
                                "couleur":"",
                                "visible":false
                             }
                          ]
                       }
                    ]
                 }'
        ]);
    }
}
